### ISSUE TITLE
Add support for submodules

### ISSUE THREAD

**Issue by CoolSpy3** [CoolSpy3/WPILibCodespaceConfigurer#2]
Currently, `configurer.py` checks for the existence of the `lib199` directory in submodules and copies a different set of files based on that distinction. It should be updated to read `.gitmodules` and dynamically edit the file to produce these results for all submodules.

https://github.com/CoolSpy3/WPILibCodespaceConfigurer/blob/3a701eaae7d46288f066ff192abd47579d986f99/configure.py#L42-L46

**Comment by brettle** [comment]
Instead, could you just not recurse when you clone in configure.py and always run `git submodule update --init` as the `postCreateCommand`?
